chain_width = 50
comment_width = 60
format_code_in_doc_comments = true
wrap_comments = true
format_strings = true
hard_tabs = false

imports_layout = "Vertical"
imports_indent = "Block"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

max_width = 80
condense_wildcard_suffixes = true

newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
